### ISSUE TITLE
npk 파일 생성 안되는 문제

### ISSUE THREAD

**Issue by J2P** [lqez/pynpk#1]
pack = npk.package('new.npk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/J2P/.pythonbrew/venvs/Python-2.7.3/ssbms/lib/python2.7/site-packages/npk/package.py", line 10, in **init**
    self.open(filename, teakey)
  File "/Users/J2P/.pythonbrew/venvs/Python-2.7.3/ssbms/lib/python2.7/site-packages/npk/package.py", line 18, in open
    raise FailToOpenPackage
npk.error.FailToOpenPackage: Fail to open package.

파일이 없는 경우에 npk 파일이 생성되지 않습니다.

**Comment by lqez** [comment]
It was not fully implemented, sorry.
Fixed up at b2c129afc734f49fcaa72992594646bbffeb0b80
